name: cartas
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: ^14.2.0
  flutter_lints: ^6.0.0
  provider: ^6.1.1
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  http: ^1.2.0
  shared_preferences: ^2.2.3
  file_picker: ^8.1.4
  image_picker: ^1.0.7
  camera: ^0.12.0+1
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  audioplayers: ^6.1.0
  marquee: ^2.2.3
  firebase_core: ^4.9.0
  firebase_messaging: ^16.2.2
  flutter_local_notifications: ^20.1.0
  firebase_database: ^12.4.1
  fl_chart: ^1.2.0
  flutter_tts: ^4.2.5
  table_calendar: ^3.2.0
  flutter_stripe: ^12.6.0


  # Autres dépendances si nécessaire


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/royal_garden_bg.png
    - assets/images/
    - assets/images/plantes/
    - assets/images/instructors/
    - assets/images/map/
    - assets/images/coloriage/
    - assets/images/boutique/
    - assets/images/detailles de les produit/
    - "assets/images/forom cumm/"
    - "assets/images/sujet populaire/"
    - assets/images/gif/
    - assets/images/jardin/
    - assets/music/
