// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB61eQB_2tBchC_O09G2tckEyfIfDNXFiE',
    appId: '1:544420623669:web:c47074c75d03c1d896487c',
    messagingSenderId: '544420623669',
    projectId: 'cartas-pfe',
    authDomain: 'cartas-pfe.firebaseapp.com',
    databaseURL: 'https://cartas-pfe-default-rtdb.firebaseio.com',
    storageBucket: 'cartas-pfe.firebasestorage.app',
    measurementId: 'G-3LF5YD1Y1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAGS3QAipCYLGRGbNtq33t52ukEWzQadk',
    appId: '1:544420623669:android:bc728bc95f383b9596487c',
    messagingSenderId: '544420623669',
    projectId: 'cartas-pfe',
    databaseURL: 'https://cartas-pfe-default-rtdb.firebaseio.com',
    storageBucket: 'cartas-pfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEnSxM062jZ8qinajrENvw8dOOtGzLJMc',
    appId: '1:544420623669:ios:ee610166044e297c96487c',
    messagingSenderId: '544420623669',
    projectId: 'cartas-pfe',
    databaseURL: 'https://cartas-pfe-default-rtdb.firebaseio.com',
    storageBucket: 'cartas-pfe.firebasestorage.app',
    iosBundleId: 'tn.cartas.cartas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEnSxM062jZ8qinajrENvw8dOOtGzLJMc',
    appId: '1:544420623669:ios:ee610166044e297c96487c',
    messagingSenderId: '544420623669',
    projectId: 'cartas-pfe',
    databaseURL: 'https://cartas-pfe-default-rtdb.firebaseio.com',
    storageBucket: 'cartas-pfe.firebasestorage.app',
    iosBundleId: 'tn.cartas.cartas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB61eQB_2tBchC_O09G2tckEyfIfDNXFiE',
    appId: '1:544420623669:web:a15aa7d724d6077196487c',
    messagingSenderId: '544420623669',
    projectId: 'cartas-pfe',
    authDomain: 'cartas-pfe.firebaseapp.com',
    databaseURL: 'https://cartas-pfe-default-rtdb.firebaseio.com',
    storageBucket: 'cartas-pfe.firebasestorage.app',
    measurementId: 'G-60HWB2RSH1',
  );
}
