import 'package:flutter/material.dart';

class LanguageProvider extends ChangeNotifier {
  Locale _locale = const Locale('fr');

  Locale get locale => _locale;

  void setLanguage(String languageCode) {
    _locale = Locale(languageCode);
    notifyListeners();
  }

  String getText(String key) {
    return _translations[_locale.languageCode]?[key] ??
        _translations['fr']?[key] ??
        key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'fr': {
      'popup_welcome': 'Bienvenue sur CARTAS',
      'popup_subtitle': 'À la découverte des plantes médicinales tunisiennes',
      'popup_start': 'Commencer',
      'onboarding_title_1': 'Votre voyage vers la phytothérapie tunisienne',
      'onboarding_desc_1': 'Découvrez la richesse des plantes médicinales tunisiennes avec une expérience innovante.',
      'onboarding_title_2': 'Nature & Intelligence',
      'onboarding_desc_2': 'L\'héritage naturel, amplifié par l\'IA. Scannez des plantes, explorez l\'herbier digital, et créez vos propres recettes dans le laboratoire virtuel.',
      'onboarding_title_3': 'Votre Bien-Être',
      'onboarding_desc_3': 'Santé naturelle & autonomie. Rejoignez une communauté passionnée et apprenez les secrets des plantes médicinales tunisiennes.',
      'next': 'Suivant',
      'start': 'Commencer',
      'skip': 'Passer',
      'choose_role': 'Choisissez votre rôle',
      'select_profile': 'Sélectionnez le profil qui vous correspond',
      'user': 'Utilisatrice',
      'specialist': 'Spécialiste',
      'therapist': 'Art-Thérapeute',
      'partner': 'Partenaire',

      // Home Screen & Bottom Nav
      'nav_home': 'Accueil',
      'nav_lab': 'Phyto Lab',
      'nav_shop': 'Boutique',
      'nav_profile': 'Profil',
      'bon_retour': 'Bon retour parmi nous',
      'conseil_jour': 'Conseil du jour',
      'voir_tout': 'Voir tout',
      'plantes_populaires': 'Plantes populaires',
      'scanner': 'Scanner',

      // Drawer Modules
      'herbier_title': 'Herbier Digital',
      'herbier_sub': 'Plantes médicinales',
      'trousse_title': 'Ma Trousse Naturelle',
      'trousse_sub': 'Ma pharmacie perso',
      'lab_title': 'Phyto Lab',
      'lab_sub': 'Laboratoire virtuel',
      'chat_title': 'Chat IA Tawhida+',
      'chat_sub': 'Assistante intelligente',
      'forum_title': 'Forum',
      'forum_sub': 'Communauté bien-être',
      'learn_title': 'Learn',
      'learn_sub': 'Modules éducatifs',
      'jeu_title': 'Tri9 el Kenz',
      'jeu_sub': 'Jeu éducatif',
      'consultation_title': 'Consultation',
      'consultation_sub': 'Spécialistes santé',
      'boutique_title': 'Boutique',
      'boutique_sub': 'Produits naturels',
      'logout': 'Déconnexion',

      // Herbier & Trousse
      'search_plant': 'Rechercher une plante...',
      'cat_all': 'Toutes',
      'cat_calmant': 'Calmant',
      'cat_digestion': 'Digestion',
      'cat_immunite': 'Immunité',
      'cat_energie': 'Énergie',
      'cat_peau': 'Peau',
      'cat_sommeil': 'Sommeil',
      'add_to_trousse': 'Ajouter à ma trousse',
      'remove_from_trousse': 'Retirer de ma trousse',
      'botanical_info': 'Info. Botanique',
      'region': 'Région',
      'my_trousse': 'Ma Trousse Naturelle',
      'no_plants_trousse': 'Votre trousse est vide.',
      'order_trousse': 'Commander ma trousse',
    },
    'en': {
      'popup_welcome': 'Welcome to CARTAS',
      'popup_subtitle': 'Discover Tunisian medicinal plants',
      'popup_start': 'Start',
      'onboarding_title_1': 'Your journey to Tunisian phytotherapy',
      'onboarding_desc_1': 'Discover the richness of Tunisian medicinal plants with an innovative experience.',
      'onboarding_title_2': 'Nature & Intelligence',
      'onboarding_desc_2': 'Natural heritage, amplified by AI. Scan plants, explore the digital herbarium, and create your own recipes in the virtual lab.',
      'onboarding_title_3': 'Your Well-Being',
      'onboarding_desc_3': 'Natural health & autonomy. Join a passionate community and learn the secrets of Tunisian medicinal plants.',
      'next': 'Next',
      'start': 'Start',
      'skip': 'Skip',
      'choose_role': 'Choose your role',
      'select_profile': 'Select the profile that matches you',
      'user': 'User',
      'specialist': 'Specialist',
      'therapist': 'Art Therapist',
      'partner': 'Partner',

      // Home Screen & Bottom Nav
      'nav_home': 'Home',
      'nav_lab': 'Phyto Lab',
      'nav_shop': 'Shop',
      'nav_profile': 'Profile',
      'bon_retour': 'Welcome back',
      'conseil_jour': 'Tip of the day',
      'voir_tout': 'See all',
      'plantes_populaires': 'Popular plants',
      'scanner': 'Scan',

      // Drawer Modules
      'herbier_title': 'Digital Herbarium',
      'herbier_sub': 'Medicinal plants',
      'trousse_title': 'My Natural Kit',
      'trousse_sub': 'Personal pharmacy',
      'lab_title': 'Phyto Lab',
      'lab_sub': 'Virtual laboratory',
      'chat_title': 'AI Tawhida+ Chat',
      'chat_sub': 'Smart assistant',
      'forum_title': 'Forum',
      'forum_sub': 'Wellness community',
      'learn_title': 'Learn',
      'learn_sub': 'Educational modules',
      'jeu_title': 'Tri9 el Kenz',
      'jeu_sub': 'Educational game',
      'consultation_title': 'Consultation',
      'consultation_sub': 'Health specialists',
      'boutique_title': 'Shop',
      'boutique_sub': 'Natural products',
      'logout': 'Logout',

      // Herbier & Trousse
      'search_plant': 'Search for a plant...',
      'cat_all': 'All',
      'cat_calmant': 'Calming',
      'cat_digestion': 'Digestion',
      'cat_immunite': 'Immunity',
      'cat_energie': 'Energy',
      'cat_peau': 'Skin',
      'cat_sommeil': 'Sleep',
      'add_to_trousse': 'Add to my kit',
      'remove_from_trousse': 'Remove from my kit',
      'botanical_info': 'Botanical Info',
      'region': 'Region',
      'my_trousse': 'My Natural Kit',
      'no_plants_trousse': 'Your kit is empty.',
      'order_trousse': 'Order my kit',
    },
    'ar': {
      'popup_welcome': 'مرحباً بكم في قرطاج',
      'popup_subtitle': 'اكتشفوا النباتات الطبية التونسية',
      'popup_start': 'ابدأ الآن',
      'onboarding_title_1': 'رحلتك نحو العلاج بالنباتات التونسية',
      'onboarding_desc_1': 'اكتشفي ثراء النباتات الطبية التونسية من خلال تجربة مبتكرة.',
      'onboarding_title_2': 'الطبيعة والذكاء',
      'onboarding_desc_2': 'إرث طبيعي معزز بالذكاء الاصطناعي. امسحي النباتات، استكشفي المعشبة الرقمية، وابتكري وصفاتك الخاصة في المختبر الافتراضي.',
      'onboarding_title_3': 'صحتك وعافيتك',
      'onboarding_desc_3': 'صحة طبيعية واستقلالية. انضمي إلى مجتمع شغوف وتعلمي أسرار النباتات الطبية التونسية.',
      'next': 'التالي',
      'start': 'ابدأي',
      'skip': 'تخطي',
      'choose_role': 'اختاري دورك',
      'select_profile': 'اختري الملف الشخصي الذي يناسبك',
      'user': 'مستخدمة',
      'specialist': 'أخصائية',
      'therapist': 'معالجة بالفن',
      'partner': 'شريكة',

      // Home Screen & Bottom Nav
      'nav_home': 'الرئيسية',
      'nav_lab': 'مختبر النباتات',
      'nav_shop': 'المتجر',
      'nav_profile': 'حسابي',
      'bon_retour': 'مرحباً بعودتك',
      'conseil_jour': 'نصيحة اليوم',
      'voir_tout': 'عرض الكل',
      'plantes_populaires': 'النباتات الشائعة',
      'scanner': 'مسح',

      // Drawer Modules
      'herbier_title': 'المعشبة الرقمية',
      'herbier_sub': 'النباتات الطبية',
      'trousse_title': 'صيدليتي الطبيعية',
      'trousse_sub': 'معالجتي الشخصية',
      'lab_title': 'مختبر النباتات',
      'lab_sub': 'مختبر افتراضي',
      'chat_title': 'محادثة الذكاء الاصطناعي',
      'chat_sub': 'مساعدة ذكية',
      'forum_title': 'المنتدى',
      'forum_sub': 'مجتمع العافية',
      'learn_title': 'تعلم',
      'learn_sub': 'وحدات تعليمية',
      'jeu_title': 'طريق الكنز',
      'jeu_sub': 'لعبة تعليمية',
      'consultation_title': 'استشارة',
      'consultation_sub': 'أخصائيو الصحة',
      'boutique_title': 'المتجر',
      'boutique_sub': 'منتجات طبيعية',
      'logout': 'تسجيل خروج',

      // Herbier & Trousse
      'search_plant': 'ابحث عن نبتة...',
      'cat_all': 'الكل',
      'cat_calmant': 'المهدئات',
      'cat_digestion': 'الهضم',
      'cat_immunite': 'المناعة',
      'cat_energie': 'الطاقة',
      'cat_peau': 'البشرة',
      'cat_sommeil': 'النوم',
      'add_to_trousse': 'أضف إلى صيدليتي',
      'remove_from_trousse': 'إزالة من صيدليتي',
      'botanical_info': 'معلومات نباتية',
      'region': 'المنطقة',
      'my_trousse': 'صيدليتي الطبيعية',
      'no_plants_trousse': 'صيدليتك فارغة.',
      'order_trousse': 'اطلب صيدليتي',
    },
  };
}